name: Request Reviewers with Added Label

on:
  pull_request:
    types: [labeled]

jobs:
  assign_reviewer_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Assign
        uses: MxShun/esmeralda@master
        # uses: marty-s-miyake/esmeralda@1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          request_reviewers: .github/workflows/esmeralda/pr_reviewers.json
          number_of_reviewers: 2
          slack_wehbook: ${{ secrets.SLACK_WEBHOOK_URL }}
