name: Request Reviewers with Added Label
on:
  pull_request:
    types: [labeled]

jobs:
  assign_reviewer_job:
    if: contains(github.event.pull_request.labels.*.name, 'team A')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Assign
        uses: MxShun/esmeralda@test/specific-label
        with:          
          github-token: ${{ secrets.GITHUB_TOKEN }}
          request_reviewers: .github/workflows/pr_reviewers.json
          # number_of_reviewers: # Optional (Default: 15)
          # class_of_reviewers: "team A: 3, team B: 3"
          # default_label: team A # Optional
          # slack_webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
