name: Request Reviewers with Added Label
on:
  pull_request:
    types: [labeled]

jobs:
  assign_reviewer_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Assign
        if: github.event.pull_request.labels.*.name == 'TEST'
        uses: MxShun/esmeralda@test/specific-label
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          request_reviewers: .github/workflows/pr_reviewers.json
          class_of_reviewers: "team A: 1, team B: 2"
          slack_webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
